services:
  discord-calendar-bot:
    image: ghcr.io/iniwa/discord-gemini-assist-calender:latest
    container_name: discord-calendar-bot
    restart: unless-stopped
    volumes:
      - /home/iniwa/docker/discord-calendar/data:/data
      - /home/iniwa/docker/discord-calendar/service_account.json:/usr/src/app/service_account.json:ro
    environment:
      - DISCORD_BOT_TOKEN=
      - GEMINI_API_KEY=
      - BOT_ADMIN_ID=
    user: "1000:1000"
