services:
  discord-calendar-bot:
    image: ghcr.io/iniwa/discord-gemini-assist-calender:latest
    container_name: discord-calendar-bot
    restart: unless-stopped
    volumes:
      - /home/iniwa/docker/discord-calendar/data:/data
    environment:
      - DISCORD_BOT_TOKEN=
      - GEMINI_API_KEY=
      # サービスアカウントのJSONキー内容を1行で設定
      - GOOGLE_CREDENTIALS_JSON=
    user: "1000:1000"
